name: Build-iOS-Deb

# البناء عند الرفع على فرع master أو تشغيل يدوي
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Theos
      uses: theos/setup-theos@master

    - name: Get Version
      run: |
        # استخراج الإصدار من ملف versionCheck
        VERSION=$(cat ./template/versionCheck.sh | sed -n 2p | tail -c 7 | head -c 5)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Deb Package
      run: |
        # بناء الملف النهائي
        make FINALPACKAGE=1
      env:
        THEOS: ${{ github.workspace }}/theos

    - name: Upload Deb Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "MyHack_v${{ env.VERSION }}.deb"
        path: "packages/*.deb"

    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
    
    - name: Add Deb to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: $(ls packages/*.deb)
        asset_name: "MyHack_v${{ env.VERSION }}.deb"
        asset_content_type: application/vnd.debian.binary-package
